# Generated by Django 4.2.6 on 2023-12-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('name_language', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Name Language')),
                ('id_country', models.CharField(max_length=3, verbose_name='id country')),
            ],
            options={
                'verbose_name': 'Name Language',
                'verbose_name_plural': 'Name Languages',
                'ordering': ['name_language'],
                'unique_together': {('name_language', 'id_country')},
            },
        ),
    ]
